apiVersion: apps/v1
kind: Deployment
metadata:
  name: extraescolares
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extraescolares
  template:
    metadata:
      labels:
        app: extraescolares
    spec:
      containers:
        - name: extraescolares-container
          image: josesamuel/extraescolares:v2
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: MONGODB_URI
              value: "mongodb+srv://20240446:aZfZsUNPZmXkAG84@labdespliegue.yf6rw.mong"
