apiVersion: v1
kind: Service
metadata:
  name: extraescolares-service
  namespace: default
spec:
  selector:
    app: extraescolares
  ports:
    - name: port-3001
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
  type: NodePort